### ISSUE TITLE
How to forecast future values using Croston Method?

### ISSUE THREAD

**Issue by KathyGCY** [antoinecarme/pyaf#109]
Hi   @antoinecarme #, I'm replicating the examples provided in this notebook [croston](https://github.com/antoinecarme/pyaf/blob/master/notebooks_sandbox/croston.ipynb)
And It appears we only have fitted values (ending on 2002-12-31 ). What if I want to forecast future values? Say I want 7-day-out forecast?

In [In. 16] we see "df2['forecast'] = coeff * df2['q_est'] / df2['a_est']" So the forecast is calculated using the q_est and a_est.

Does that mean to forecast, I would do forecast 7-day-out q_est and a_est first? And after I arima/ets/bsts/other-TS forecast the q_enst and a_est, I then use the formula above to get the 7-day-out forecast? @

**Comment by antoinecarme** [comment]
Hi @KathyGCY,

Thanks for using PyAF.

This notebook is a notebook I used for prototyping (before Croston method is implemented). I keep track of everything .sorry.

Croston method can be used like any other model, You can find some python examples here : 

https://github.com/antoinecarme/pyaf/tree/master/tests/croston

Your feedback is welcome.

**Comment by antoinecarme** [comment]
Added a README file for warning about the notebooks_sandbox directory : 

https://github.com/antoinecarme/pyaf/blob/master/notebooks_sandbox/README.md

**Comment by anuliketat** [comment]
Hi @antoinecarme I'm trying to replicate R's Croston function in Python. I need some help in building that function from scratch.
Also PyAFs auto forecasting engine is taking too long to train. Is it a bug? How to overcome it? Thanks.

**Comment by antoinecarme** [comment]
Closing issue after no response for 30 days. Not blocking.

Please repoen if needed.
