### ISSUE TITLE
FileNotFoundError: [WinError 2] "dot" not found   in path.

### ISSUE THREAD

**Issue by vhphan** [antoinecarme/pyaf#113]
1) I am getting the following error, "FileNotFoundError: [WinError 2] "dot" not found   in path.", when running PyAF_Hierarchical_FrenchWineExportation.ipynb
The cell:
# create a model to plot the hierarchy.
import pyaf.HierarchicalForecastEngine as hautof
lEngine = hautof.cHierarchicalForecastEngine()
lSignalHierarchy = lEngine.plot_Hierarchy(French_Wine_Export_in_Euros_DF , "Month", "Signal", 1, 
                                          lHierarchy, None);

The output:
INFO:pyaf.std:START_HIERARCHICAL_PLOTTING
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
C:\ProgramData\Anaconda3\envs\ds2_clone\lib\site-packages\pydot.py in create(self, prog, format, encoding)
   1914                 arguments=arguments,
-> 1915                 working_dir=tmp_dir,
   1916             )

C:\ProgramData\Anaconda3\envs\ds2_clone\lib\site-packages\pydot.py in call_graphviz(program, arguments, working_dir, **kwargs)
    135         stdout=subprocess.PIPE,
--> 136         **kwargs
    137     )

C:\ProgramData\Anaconda3\envs\ds2_clone\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    708                                 errread, errwrite,
--> 709                                 restore_signals, start_new_session)
    710         except:

C:\ProgramData\Anaconda3\envs\ds2_clone\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
    996                                          os.fspath(cwd) if cwd is not None else None,
--> 997                                          startupinfo)
    998             finally:

FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-19-c716ad2dbe2f> in <module>
      5 
      6 lSignalHierarchy = lEngine.plot_Hierarchy(French_Wine_Export_in_Euros_DF , "Month", "Signal", 1, 
----> 7                                           lHierarchy, None);

C:\ProgramData\Anaconda3\envs\ds2_clone\lib\site-packages\pyaf\HierarchicalForecastEngine.py in plot_Hierarchy(self, iInputDS, iTime, iSignal, iHorizon, iHierarchy, iExogenousData)
     86         lSignalHierarchy = self.create_signal_hierarchy(iInputDS, iTime, iSignal, iHorizon, iHierarchy, iExogenousData);
     87         lSignalHierarchy.create_HierarchicalStructure();
---> 88         lSignalHierarchy.plot();
     89         return lSignalHierarchy;
     90 

C:\ProgramData\Anaconda3\envs\ds2_clone\lib\site-packages\pyaf\TS\SignalHierarchy.py in plot(self, name)
    215                         lProp = self.mAvgHistProp[signal][col1] * 100;
    216                         lAnnotations[str(signal) +"_" + col1] = ('%2.2f %%' % lProp)
--> 217         tsplot.plot_hierarchy(self.mStructure, lAnnotations, name)
    218         lPlotTime = time.time() - start_time;
    219         logger.info("END_HIERARCHICAL_PLOTTING_TIME_IN_SECONDS " + str(lPlotTime))

C:\ProgramData\Anaconda3\envs\ds2_clone\lib\site-packages\pyaf\TS\Plots.py in plot_hierarchy(structure, iAnnotations, name)
    235     else:
    236         from IPython.display import Image, display
--> 237         plot1 = Image(graph.create_png())
    238         display(plot1)

C:\ProgramData\Anaconda3\envs\ds2_clone\lib\site-packages\pydot.py in new_method(f, prog, encoding)
   1721                 """Refer to docstring of method `create`."""
   1722                 return self.create(
-> 1723                     format=f, prog=prog, encoding=encoding)
   1724             name = 'create_{fmt}'.format(fmt=frmt)
   1725             self.__setattr__(name, new_method)

C:\ProgramData\Anaconda3\envs\ds2_clone\lib\site-packages\pydot.py in create(self, prog, format, encoding)
   1920                 args[1] = '"{prog}" not found in path.'.format(
   1921                     prog=prog)
-> 1922                 raise OSError(*args)
   1923             else:
   1924                 raise

FileNotFoundError: [WinError 2] "dot" not found in path.

## Output of script https://github.com/antoinecarme/pyaf/blob/master/tests/basic_checks/platform_info.py:
PYAF_SYSTEM_DEPENDENT_VERSION_INFO ('Cython_version', '0.29.4')
PYAF_SYSTEM_DEPENDENT_VERSION_INFO ('keras_version', 'NOT_INSTALLED')
PYAF_SYSTEM_DEPENDENT_VERSION_INFO ('matplotlib_version', '3.1.0')
PYAF_SYSTEM_DEPENDENT_VERSION_INFO ('numpy_version', '1.16.4')
PYAF_SYSTEM_DEPENDENT_VERSION_INFO ('pandas_version', '0.24.1')
PYAF_SYSTEM_DEPENDENT_VERSION_INFO ('pip_version', '19.0.1')
PYAF_SYSTEM_DEPENDENT_VERSION_INFO ('pydot_version', '1.4.1')
PYAF_SYSTEM_DEPENDENT_VERSION_INFO ('python_implementation', 'CPython')
PYAF_SYSTEM_DEPENDENT_VERSION_INFO ('python_version', '3.6.6')
PYAF_SYSTEM_DEPENDENT_VERSION_INFO ('scipy_version', '1.1.0')
PYAF_SYSTEM_DEPENDENT_VERSION_INFO ('setuptools_version', '41.0.1')
PYAF_SYSTEM_DEPENDENT_VERSION_INFO ('sklearn_version', '0.20.2')
PYAF_SYSTEM_DEPENDENT_VERSION_INFO ('sqlalchemy_version', '1.2.18')
PYAF_SYSTEM_DEPENDENT_VERSION_INFO ('system_platform', 'Windows-10-10.0.17134-SP0')
PYAF_SYSTEM_DEPENDENT_VERSION_INFO ('system_processor', 'Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')
PYAF_SYSTEM_DEPENDENT_VERSION_INFO ('system_uname', uname_result(system='Windows', node='XPS-VHP', release='10', version='10.0.17134', machine='AMD64', processor='Intel64 Family 6 Model 94 Stepping 3, GenuineIntel'))
PYAF_SYSTEM_DEPENDENT_VERSION_INFO ('xgboost_version', '0.82')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('ALLUSERSPROFILE', 'C:\\ProgramData')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('ANDROID_HOME', 'C:\\Users\\vhphan\\AppData\\Local\\Android\\Sdk')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('APPDATA', 'C:\\Users\\vhphan\\AppData\\Roaming')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('CFLAGS', ' -MD -GL')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('CHOCOLATEYINSTALL', 'C:\\ProgramData\\chocolatey')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('CHOCOLATEYLASTPATHUPDATE', 'Mon Sep 11 23:39:51 2017')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('CLICOLOR', '1')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('CMAKE_GENERATOR', 'Visual Studio 14 2015 Win64')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('COMMANDPROMPTTYPE', 'Native')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('COMMONPROGRAMFILES', 'C:\\Program Files\\Common Files')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('COMMONPROGRAMFILES(X86)', 'C:\\Program Files (x86)\\Common Files')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('COMMONPROGRAMW6432', 'C:\\Program Files\\Common Files')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('COMPUTERNAME', 'XPS-VHP')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('COMSPEC', 'C:\\WINDOWS\\system32\\cmd.exe')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('CONDA_DEFAULT_ENV', 'ds2_clone')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('CONDA_EXE', 'C:\\ProgramData\\Anaconda3\\Scripts\\conda.exe')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('CONDA_PREFIX', 'C:\\ProgramData\\Anaconda3\\envs\\ds2_clone')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('CONDA_PREFIX_1', 'C:\\ProgramData\\Anaconda3')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('CONDA_PROMPT_MODIFIER', '(ds2_clone) ')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('CONDA_PYTHON_EXE', 'C:\\ProgramData\\Anaconda3\\python.exe')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('CONDA_SHLVL', '2')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('CURDIR', 'C:\\Program Files (x86)\\Microsoft Visual C++ Build Tools\\')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('CURRENTDIR', 'C:\\Users\\vhphan\\PycharmProjects\\misc')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('CXXFLAGS', ' -MD -GL')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('DISTUTILS_USE_SDK', '1')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('DRIVERDATA', 'C:\\Windows\\System32\\Drivers\\DriverData')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('FOLDER', 'x86')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('FPS_BROWSER_APP_PROFILE_STRING', 'Internet Explorer')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('FPS_BROWSER_USER_PROFILE_STRING', 'Default')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('FRAMEWORKDIR', 'C:\\WINDOWS\\Microsoft.NET\\Framework64')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('FRAMEWORKDIR64', 'C:\\WINDOWS\\Microsoft.NET\\Framework64')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('FRAMEWORKVERSION', 'v4.0.30319')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('FRAMEWORKVERSION64', 'v4.0.30319')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('GDAL_DATA', 'C:\\ProgramData\\Anaconda3\\envs\\ds2_clone\\Library\\share\\gdal')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('GEOTIFF_CSV', 'C:\\ProgramData\\Anaconda3\\envs\\ds2_clone\\Library\\share\\epsg_csv')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('GIT_PAGER', 'cat')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('GYP_MSVS_VERSION', '2015')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('HOMEDRIVE', 'C:')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('HOMEPATH', '\\Users\\vhphan')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('INCLUDE', 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\INCLUDE;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.10240.0\\ucrt;C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\include\\um;C:\\Program Files (x86)\\Windows Kits\\8.1\\include\\shared;C:\\Program Files (x86)\\Windows Kits\\8.1\\include\\um;C:\\Program Files (x86)\\Windows Kits\\8.1\\include\\winrt;')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('IPY_INTERRUPT_EVENT', '2992')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('JPY_INTERRUPT_EVENT', '2992')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('JPY_PARENT_PID', '3012')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('LDFLAGS_SHARED', ' -LTCG ucrt.lib')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('LIB', 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\LIB\\amd64;C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.10240.0\\ucrt\\x64;C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\lib\\um\\x64;C:\\Program Files (x86)\\Windows Kits\\8.1\\lib\\winv6.3\\um\\x64;')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('LIBPATH', 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\LIB\\amd64;C:\\WINDOWS\\Microsoft.NET\\Framework64\\v4.0.30319;C:\\WINDOWS\\Microsoft.NET\\Framework64\\;References\\CommonConfiguration\\Neutral;\\Microsoft.VCLibs\\14.0\\References\\CommonConfiguration\\neutral;')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('LOCALAPPDATA', 'C:\\Users\\vhphan\\AppData\\Local')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('LOGONSERVER', '\\\\XPS-VHP')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('MKL_THREADING_LAYER', 'GNU')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('MOZ_PLUGIN_PATH', 'C:\\Program Files (x86)\\Foxit Software\\Foxit Reader\\plugins\\')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('MPLBACKEND', 'module://ipykernel.pylab.backend_inline')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('MSSDK', '1')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('MSYS2_ARG_CONV_EXCL', '/AI;/AL;/OUT;/out')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('MSYS2_ENV_CONV_EXCL', 'CL')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('NETFXSDKDIR', 'C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('NUMBER_OF_PROCESSORS', '8')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('ONEDRIVE', 'C:\\Users\\vhphan\\OneDrive')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('ONEDRIVECONSUMER', 'C:\\Users\\vhphan\\OneDrive')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('OS', 'Windows_NT')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('PAGER', 'cat')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('PATH', 'C:\\ProgramData\\Anaconda3\\envs\\ds2_clone\\Library\\bin;C:\\Program Files (x86)\\MSBuild\\14.0\\bin\\amd64;C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64;C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\VCPackages;C:\\WINDOWS\\Microsoft.NET\\Framework64\\v4.0.30319;C:\\WINDOWS\\Microsoft.NET\\Framework64\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\bin\\x64;C:\\Program Files (x86)\\Windows Kits\\8.1\\bin\\x86;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v10.0A\\bin\\NETFX 4.6.1 Tools\\x64\\;C:\\ProgramData\\Anaconda3\\envs\\ds2_clone;C:\\ProgramData\\Anaconda3\\envs\\ds2_clone\\Library\\mingw-w64\\bin;C:\\ProgramData\\Anaconda3\\envs\\ds2_clone\\Library\\usr\\bin;C:\\ProgramData\\Anaconda3\\envs\\ds2_clone\\Library\\bin;C:\\ProgramData\\Anaconda3\\envs\\ds2_clone\\Scripts;C:\\ProgramData\\Anaconda3\\envs\\ds2_clone\\bin;C:\\ProgramData\\Anaconda3\\condabin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files\\Dell\\DW WLAN Card;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files\\WIDCOMM\\Bluetooth Software;C:\\Program Files\\WIDCOMM\\Bluetooth Software\\syswow64;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\wamp\\bin\\php\\php5.6.19;C:\\ProgramData\\ComposerSetup\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn;C:\\Program Files (x86)\\Google\\Google Apps Sync;C:\\Program Files (x86)\\Google\\Google Apps Migration;C:\\Program Files\\PuTTY;C:\\Program Files\\Git\\cmd;C:\\ProgramData\\chocolatey\\bin;C:\\ProgramData\\Anaconda3;C:\\Program Files (x86)\\Google\\Cloud SDK\\google-cloud-sdk\\bin;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\PostgreSQL\\10\\bin;C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\osgeo;C:\\Program Files\\Google\\Google Apps Sync;C:\\Program Files\\Google\\Google Apps Migration;C:\\Program Files (x86)\\Graphviz2.38\\bin;C:\\ProgramData\\Anaconda3\\Library\\bin;C:\\Program Files\\nodejs;C:\\Program Files (x86)\\WinRAR;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Google\\Chrome\\Application;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0\\bin;C:\\Users\\vhphan\\AppData\\Local\\JSONBuddy;C:\\Users\\vhphan\\AppData\\Roaming\\Composer\\vendor\\bin;C:\\Users\\vhphan\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\Heroku\\bin;C:\\Users\\vhphan\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\vhphan\\Downloads\\VSCode-win32-x64-1.14.2\\bin;C:\\wamp\\bin\\php\\php7.0.4;C:\\Users\\vhphan\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\OSGeo4W64\\bin;C:\\Users\\vhphan\\ogr2ogr\\bin\\gdal;C:\\Users\\vhphan\\ogr2ogr\\bin\\gdal-data;C:\\ProgramData\\Anaconda3\\Scripts;C:\\Program Files (x86)\\Graphviz2.38\\bin;C:\\ProgramData\\Anaconda3\\Library\\bin;C:\\Users\\vhphan\\AppData\\Roaming\\npm;C:\\Program Files (x86)\\WinRAR;C:\\Program Files\\JetBrains\\PhpStorm 2019.1.1\\bin;.;C:\\Program Files\\JetBrains\\PyCharm 2019.1.2\\bin;.;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0\\bin;.;C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pywin32_system32;C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pywin32_system32;c:\\programdata\\anaconda3\\lib\\site-packages\\pywin32_system32;c:\\programdata\\anaconda3\\lib\\site-packages\\pywin32_system32;C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pywin32_system32;C:\\Program Files (x86)\\Windows Kits\\10\\bin\\\\x86;C:\\ProgramData\\Anaconda3\\envs\\ds2_clone\\lib\\site-packages\\numpy\\.libs')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('PATHEXT', '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('PHPSTORM', 'C:\\Program Files\\JetBrains\\PhpStorm 2019.1.1\\bin;')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('PLATFORM', 'X64')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('POSTGIS_ENABLE_OUTDB_RASTERS', '1')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('POSTGIS_GDAL_ENABLED_DRIVERS', 'GTiff PNG JPEG GIF XYZ DTED USGSDEM AAIGrid')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('PROCESSOR_ARCHITECTURE', 'AMD64')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('PROCESSOR_IDENTIFIER', 'Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('PROCESSOR_LEVEL', '6')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('PROCESSOR_REVISION', '5e03')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('PROGRAMDATA', 'C:\\ProgramData')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('PROGRAMFILES', 'C:\\Program Files')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('PROGRAMFILES(X86)', 'C:\\Program Files (x86)')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('PROGRAMW6432', 'C:\\Program Files')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('PROJ_LIB', 'C:\\ProgramData\\Anaconda3\\envs\\ds2_clone\\Library\\share')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('PROMPT', '(ds2_clone) $P$G')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('PSMODULEPATH', 'C:\\Program Files (x86)\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files (x86)\\Google\\Cloud SDK\\google-cloud-sdk\\platform\\PowerShell')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('PUBLIC', 'C:\\Users\\Public')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('PYCHARM', 'C:\\Program Files\\JetBrains\\PyCharm 2019.1.2\\bin;')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('PYTHON', 'C:\\ProgramData\\Anaconda3\\python.EXE')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('PY_VCRUNTIME_REDIST', '\\vcruntime140.dll')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('SESSIONNAME', 'Console')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('SYSTEMDRIVE', 'C:')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('SYSTEMROOT', 'C:\\WINDOWS')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('TEMP', 'C:\\Users\\vhphan\\AppData\\Local\\Temp')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('TERM', 'xterm-color')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('TMP', 'C:\\Users\\vhphan\\AppData\\Local\\Temp')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('UCRTCONTENTROOT', 'C:\\Program Files (x86)\\Windows Kits\\10\\')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('UCRTVERSION', '10.0.10240.0')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('UNIVERSALCRTSDKDIR', 'C:\\Program Files (x86)\\Windows Kits\\10\\')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('USERDOMAIN', 'XPS-VHP')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('USERDOMAIN_ROAMINGPROFILE', 'XPS-VHP')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('USERNAME', 'vhphan')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('USERPROFILE', 'C:\\Users\\vhphan')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('VBOX_MSI_INSTALL_PATH', 'C:\\Program Files\\Oracle\\VirtualBox\\')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('VCINSTALLDIR', 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('VCTARGETSPATH', 'C:\\Program Files (x86)\\MSBuild\\Microsoft.Cpp\\v4.0\\V140\\')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('VS140COMNTOOLS', 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('VSINSTALLDIR', 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('VSREGKEY', 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\Microsoft\\VisualStudio\\14.0')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('VS_MAJOR', '14')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('VS_VERSION', '14.0')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('VS_YEAR', '2015')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('WIN', '10')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('WINDIR', 'C:\\WINDOWS')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('WINDOWSLIBPATH', 'References\\CommonConfiguration\\Neutral')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('WINDOWSSDKDIR', 'C:\\Program Files (x86)\\Windows Kits\\8.1\\')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('WINDOWSSDKLIBVERSION', 'winv6.3\\')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('WINDOWSSDK_EXECUTABLEPATH_X64', 'C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v10.0A\\bin\\NETFX 4.6.1 Tools\\x64\\')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('WINDOWSSDK_EXECUTABLEPATH_X86', 'C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v10.0A\\bin\\NETFX 4.6.1 Tools\\')
PYAF_SYSTEM_DEPENDENT_ENVIRONMENT_VARIABLE ('_CONDA_SET_GDAL_DATA', 'C:\\Program Files\\PostgreSQL\\10\\gdal-data')

**Comment by antoinecarme** [comment]
@vhphan 

Thanks for your interest in PyAF. Seems some dependency of dependency is missing (pydot depends on dot/graphviz). 

Can you please check the fix described on this page : 

https://stackoverflow.com/questions/26349314/how-can-i-use-conda-to-install-pydot

Your feedback is welcome.

**Comment by antoinecarme** [comment]
Closing issue after no response for 30 days. Not blocking.

Please repoen if needed.
