### ISSUE TITLE
Add a Pypi version

### ISSUE THREAD

**Issue by firmai** [antoinecarme/pyaf#119]
While issue reports are always welcome, and you are free to use any form to submit these, the following points are to be considered for an easier processing and more productivity:

1. The issue must be a bug or a feature request.
2. A description is needed as source code and/or a link to a dataset for which the problem arises (please simplify the code, anonymize the dataset etc).
3. information on different software versions used (pyaf, numpy, pandas, scikit-learn etc). The output of the following script should be enough : https://github.com/antoinecarme/pyaf/blob/master/tests/basic_checks/platform_info.py

**Comment by firmai** [comment]
I am working on a new package, and I literally can't include your package because I can't get it working in my setup file for eg.


      packages=['atspy'],
      install_requires=[
          'pandas',
          'numpy==1.17.4',
          'scipy',
          'numba',
          'datetime',
          'pmdarima',
          'pydot',

We have lost the option to install dependencies from links (spam reasons)

**Comment by antoinecarme** [comment]
Hi @firmai 

Thanks for using PyAF. 

I am not really a specialist when it comes to packaging and make packages available on different platforms. PyAF started as a toy project and was not intended to be distributed outside the github channel.

Using PyAF in a ensemble is a good feature by the way ;)

Not sure I can help too much here, but if you really need PyAF as a dependency on Pypi, Please investigate the use of direct github links for the install (git+http) 

https://github.com/pypa/pip/issues/6301

If someone is interested in working on this issuse, they are welcome.

**Comment by firmai** [comment]
So your PyAF package ```forecast``` produces a lot of additional outputs apart from the forecast itself, could any of these additional columns be used in an ensemble as well. Is there any documentation that I can look at to identify what each of these columns mean. Thanks in advance.

**Comment by antoinecarme** [comment]
Not sure if these outputs can be used in an ensemble , some are partial desriptions of the signal decomposition (PyAF internal). Anyway, the output is a pandas data-frame and you can play wit hit the way you want.

These are named in a (hopefully) self-explaining way.

I started a issue some time ago to describe the algorithmic aspects : 

https://github.com/antoinecarme/pyaf/issues/35

It links to a doc/jupyter notebook here : 

https://github.com/antoinecarme/pyaf/blob/master/docs/PyAF_Algorithmic_Aspects.ipynb

Not sure this doc is up-to-date as some models were added since then.

**Comment by antoinecarme** [comment]
Fixed in release 1.2.

**Comment by antoinecarme** [comment]
@firmai 

I get this message when I try to upload a new release for the PyPI package. Can you please remove this pyaf package on POyPI ? email sent.

Thanks in advance

```

$ /home/antoine/.local/bin/twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Enter your username: antoinecarme
Enter your password: 
Uploading pyaf-1.2-py2.py3-none-any.whl
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 8.49k/8.49k [00:00<00:00, 11.9kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 403 Client Error: The user 'antoinecarme' isn't allowed to upload to project 'pyaf'. See https://pypi.org/help/#project-name for more information. for url: https://upload.pypi.org/legacy/
```

**Comment by firmai** [comment]
Hey, yes it should work now, otherwise give it some time to propagate.

**Comment by antoinecarme** [comment]
Fantastic !!! Something starts working. Thanks a lot for the quick answer.

Could you please perform an install on your side and give me your feedback ?

FR greets NZ ;-)

**Comment by antoinecarme** [comment]
https://pypistats.org/packages/pyaf
