### ISSUE TITLE
Future Warning regarding DateTime_Functions - series.dt.weekofyear

### ISSUE THREAD

**Issue by TomKetOS** [antoinecarme/pyaf#153]
Hello Antoinecarme,
thanks a lot for all your work done here.
I'm very new in python and programming at all, but thanks to your dokumentation i could start working with forecasting.

I got a FutureWaring as follows:

D:\Python\WPy64-3810\python-3.8.1.amd64\lib\site-packages\pyaf\TS\DateTime_Functions.py:50: FutureWarning:

Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.

I try to modifiy but that seem to make the problem bigger:

class cDateTime_Helper:

    def __init__(self):
        pass

    def get_week_of_month(self, series):
        lFirstDayOfMonth = series - pd.to_timedelta(series.dt.day - 1, unit='D')
        return series.dt.weekofyear - lFirstDayOfMonth.dt.weekofyear + 1
        #return series.dt.isocalendar().week - lFirstDayOfMonth.dt.isocalendar() + 1

thanks a lot
Thomas

**Comment by antoinecarme** [comment]
Hi @TomKetOS 

Thanks for your intereset in PAF. 

Your fix is OK. 

The warning is related to newer versions of python . I try to keep pPyAF compatiblee with newer versions. Latest tested is 3.7.

There is a work in progress around that :

https://github.com/antoinecarme/pyaf/issues/149

**Comment by antoinecarme** [comment]
You probably need this : 

```
def get_week_of_month(self, series):
    lFirstDayOfMonth = series - pd.to_timedelta(series.dt.day - 1, unit='D')
    return series.dt.isocalendar().week - lFirstDayOfMonth.dt.isocalendar().week + 1
```

**Comment by antoinecarme** [comment]
Fixed.
