### ISSUE TITLE
New observations

### ISSUE THREAD

**Issue by artrune** [antoinecarme/pyaf#161]
I went reading both PyPi the readme here and also a few examples in the doc section but I couldn't find information whether I need to re traing the model when I have a new observations or if there's a way to just include that new observation?

Thanks alot!

**Comment by antoinecarme** [comment]
Hi @artrune 

Thanks for using PyAF. 

PyAF does not allow updating the model in any way. The training process is designed and optimized to be very fast and rebuilding a model with the full updated data should not take too much time.

I am very interested if you have a dataset and a description of your use case. Data and Python scripts are welcome.

**Comment by artrune** [comment]
I don't particularly have any code yet to explain this, but suppose you are observing a few hundred different measurements to which you have a few months worth of history, Lets say for some of those measurements you would always like to forecast, and so you forecast for 20 of those measurements, however whenever there's a new observation it would be ideal or awesome if you could just "slot in the new observation" and then get a new forecast (Without needing to analyze all your data again)

I understand that because of how the package might work it might not be possible or could be tedious to implement. But thats an example of why I would love that feature.

**Comment by antoinecarme** [comment]
You probabaly need to test this a real dataset to see how fast it is to train a model in a real use case !!! A dataset with thousands of rows (time points), takes a few minutes to generate a fresh model.  


Examplecs of large datasets here : 

https://github.com/antoinecarme/pyaf/tree/master/tests/long_term_forecasts

**Comment by artrune** [comment]
I think what you just told me enforces the idea that it would be good to just update a model, dont you think? (Atleast for real time environments)

And thanks for the examples will try those ASAP!

**Comment by antoinecarme** [comment]
The point is that adding a few points to an existing pyaf model does not make a valid pyaf model. Training is not optional.

**Comment by artrune** [comment]
That makes sense @antoinecarme thanks again for pointing me to the large samples and your tmie!

**Comment by antoinecarme** [comment]
#InterestingStuffForTheRoadmap #TobeInvestigated
