### ISSUE TITLE
Cleanup of README file

### ISSUE THREAD

**Issue by shaido987** [antoinecarme/pyaf#174]
The README.md file has some (minor) grammatical and punctuation issues that interrupt the reading flow. Some examples:
- Missing punctuation (lines, 57, 200, 202, etc.)
- Unnecessary capitalized words (lines 73, 91, etc.)
- Additional spaces around commas (e.g., line 96)
- NumPy, SciPy and Pandas should be properly capitalized as they are names.

For the Python example code in the README, [PEP8](https://www.python.org/dev/peps/pep-0008/#other-recommendations) recommends not using spaces around the = sign when used to indicate keyword arguments.

The above are all very minor and low priority issues but fixing them can be done without any large effort.

**Comment by antoinecarme** [comment]
@shaido987 

Thanks a lot. These changes are of course valuable for PyAF users.

I will review the pull request.

**Comment by antoinecarme** [comment]
Related pull request : 

#173

**Comment by antoinecarme** [comment]
@shaido987 

I assigned this issue to you. Up to you to close it.

**Comment by shaido987** [comment]
@antoinecarme 

Sure, I will close it for now as the PR is merged. If there is anything more in the future I will open up a new issue.

**Comment by antoinecarme** [comment]
Perfect!! Thanks a lot.
