### ISSUE TITLE
Feature request - exogenous data in forecasting

### ISSUE THREAD

**Issue by ian-grover** [antoinecarme/pyaf#204]
Hi! 

I am looking at this package as a very useful tool for a project I plan to start. I have been reading the documentation and examples and want to understand something a bit further.

There is functionality for adding additional time-series data along with the target/signal variable through the exogenous data argument (and I am happy to see this is also possible for hierarchical modelling) but it appears that this function is not available in the forecasting function. 

I would like to be able to adjust a parameter and see how the forecast varies. From what I have read, I am not sure this is possible because while the exogenous data can be provided upon training, it does not seem to be provided with the input for forecasting. 

I am afraid my theoretical knowledge of these tools is lacking a bit, but it feels that if the input data is provided for the forecast up until the point where the data stops, it would be practical to also provide the exogenous data in the same way?

In the example [notebook](https://github.com/antoinecarme/pyaf/blob/master/docs/PyAF_Exogenous.ipynb) it says:
> In addition to the training dataset, the user can provide an external table with exogenous variables data. This table is merged with the signal dataset when exogenous vairables values are need (either when training the model or when producing forecasts).

But it is not clear to me from the code (and the example) where this is occurring? If it is occurring, could you advise if there is a procedure where I could alter some of the exogenous data after training (say on the final timestep) to see how the forecast is changed?

Many thanks!
Ian

**Comment by antoinecarme** [comment]
@ian-grover 

Short answer : if this is a feature request, as of 2022-06-30, with PyAF , version 3.0, what you are asking for is not feasible.

Longer answer : PyAF uses all the available signal and exogenous data to train a model and get a forecast. If you change the data after the training, you have to train a new model based on the new data. We make all what a is possible to shorten the training time (code optimization, columnar design, CPU/parallelization, etc). Retraining a model, should not be a time-consuming task. Please file an issue about that if it is a real problem (with a dataset, script , etc).

**Comment by antoinecarme** [comment]
Closing.
