### ISSUE TITLE
SignalDecomposition and TS_datasets missing?

### ISSUE THREAD

**Issue by peterdcotton** [antoinecarme/pyaf#37]
download_all_stock_prices.py: 

import SignalDecomposition as SigDec
import TS_datasets as tsds

tsds.download_yahoo_stock_prices();

**Comment by antoinecarme** [comment]
YES! Thanks a lot ... too old file. I will update it ASAP...

**Comment by antoinecarme** [comment]
I updated this file. 
These datasets are only to be downloaded once. I

**Comment by antoinecarme** [comment]
I used these datasets some time ago for benchmarking. There is a copy in another repository 

 https://github.com/antoinecarme/TimeSeriesData
https://github.com/antoinecarme/TimeSeriesData/tree/master/YahooFinance

You can add your own datasets there too.

Feel free to adapt/improve this code ... IT is a little bit yours now !!!

**Comment by antoinecarme** [comment]
These seems to be another copy of the same file. updated it also.

**Comment by antoinecarme** [comment]
Be aware that these benchmarks (even the downloads) may take too much CPU time (parallelized on 24-core machine).

If you have access to a better machine ... let me know.

**Comment by peterdcotton** [comment]
Yes it is keeping my 6-Core Xeon busy! 

I do notice pesky little read_csv() errors (from your repo direct) in the stand alone examples, but not in the benchmark tests. I'll play a bit and formulate the issue a bit more clearly, or resolve.
