### ISSUE TITLE
Certificate failure Python 3.6

### ISSUE THREAD

**Issue by peterdcotton** [antoinecarme/pyaf#38]
This is not an issue with PyAF. 

However, in case anyone else should encounter read_csv() failures on macosx when running examples, refer

https://bugs.python.org/issue28150

or 

http://stackoverflow.com/questions/41691327/ssl-sslerror-ssl-certificate-verify-failed-certificate-verify-failed-ssl-c

**Comment by antoinecarme** [comment]
I just tested on python 3.5
Can you please take care of this issue ?

**Comment by peterdcotton** [comment]
I will take care of it.

**Comment by peterdcotton** [comment]
Max users of Python 3.6 can resolve this issue by opening Python 3.6 in Finder /Applications and double clicking on the Install Cerfiticates.command  
![install_certificates](https://cloud.githubusercontent.com/assets/24592491/23771087/b75b1d2c-04e3-11e7-99b2-5e74f3a77a44.png)

**Comment by antoinecarme** [comment]
This seems to be a very new "feature" of python 3.6. see https://lwn.net/Articles/711954/. 

read_csv allows reading (compressed) csv files on a HTTPS link by using OpenSSL among a lot of interesting possibilities.

Python is probably going to force using the system underlying SSL layer (changes for windows, not for unix).

We probably need to separate this kind of issue by testing against a 3.5, if something fails on 3.6 and does not on 3.5 then ....

For the moment, we can only configure SSL on windows to make it work.

**Comment by antoinecarme** [comment]
will wait until python ssl support stabilizes.

**Comment by antoinecarme** [comment]
Python 3.6 support addded (#78). This issue should be closed now. Reopen idf needed.
