### ISSUE TITLE
Fails to load modules

### ISSUE THREAD

**Issue by mgiangreco** [antoinecarme/pyaf#59]
I installed pyaf via pip, and when I ask for packages in my environment ("conda list"), pyaf is listed.

However, when I try to import the modules I get this error:

import pyaf.ForecastEngine as autof
Traceback (most recent call last):

  File "<ipython-input-4-ed7d0a0b8090>", line 1, in <module>
    import pyaf.ForecastEngine as autof

ImportError: No module named pyaf.ForecastEngine

**Comment by antoinecarme** [comment]
@mgiangreco ,
I do not use anything other than standard python3 and ipython, and jupyter notebook.
Just checked, with ipthon , it works.

Can you check your anaconda environment, to be sure that pyaf parent directory is in your PYTHONPATH ?

**Comment by antoinecarme** [comment]
Just ot add, travis-ci checks are OK

https://travis-ci.org/antoinecarme/pyaf

travis-ci runs a lot of scripts and checks their logs against stored versions.

Please double check tour environment.

**Comment by mgiangreco** [comment]
I am using Python 2. Is your package compatible with Python 2?

**Comment by antoinecarme** [comment]
PyAF does not work with python2 !!!
