### ISSUE TITLE
Add ability to specify confidence interval 

### ISSUE THREAD

**Issue by mgiangreco** [antoinecarme/pyaf#60]
Great package. Would be nice to add the ability to specify the confidence interval used for generating the Upper_ and Lower_ bound predictions (e.g. 90%, 75%, 50%, etc.)

**Comment by antoinecarme** [comment]
@mgiangreco 

Thanks.

Sure , it is possible to add the possibility to customize the confidence interval. 95% is used by default, and for the majority of statisticians it covers the most interesting use cases.

Will not have the necessary bandwidth for the next two months ... but I add it to my planning. If you are interested in adding it (expect more test scripts than code ;), you are welcome.

**Comment by antoinecarme** [comment]
Until a fix is implemented, a work around is to change the value of 1.96 by the desired z-value (file TS/TimeSeriesModel.py).  

see https://en.wikipedia.org/wiki/Confidence_interval for the z-values for 90%, 75%, 50% etc.
