### ISSUE TITLE
Error while running PYAF

### ISSUE THREAD

**Issue by dineshgit** [antoinecarme/pyaf#61]
I'm planning to use PYAF for one of my projects and I am urgently trying to get this up and running, please help.

Upon running the command below:

import pyaf.ForecastEngine as autof
lEngine = autof.cForecastEngine()
lEngine.train(ozone_dataframe , 'Month' , 'Ozone', 12);

I got this error:

![image](https://user-images.githubusercontent.com/20434896/29527045-20667704-86ca-11e7-978e-2fcbf5ce513b.png)

Could someone please help me with this error ?

**Comment by antoinecarme** [comment]
Hi @dineshgit ,

The code snippet you pasted does not work... name 'ozone_dataframe' is not defined

Otherwise, I am sorry, I cannot help with numpy dll errors. Google is your friend. 

Good luck.

**Comment by dineshgit** [comment]
The code snippet is from the tutorial here:

https://github.com/antoinecarme/pyaf/blob/master/docs/PyAF_Introduction.ipynb

**Comment by antoinecarme** [comment]
Yes. I see, but the code in a jupyter notebook must be extracted/pasted starting from the beginning of the page !!!

**Comment by dineshgit** [comment]
import pandas as pd
csvfile_link = "https://raw.githubusercontent.com/antoinecarme/TimeSeriesData/master/ozone-la.csv"
ozone_dataframe = pd.read_csv(csvfile_link);

import datetime
ozone_dataframe['Month'] = ozone_dataframe['Month'].apply(lambda x : datetime.datetime.strptime(x, "%Y-%m"))
ozone_dataframe.head()

%matplotlib inline  
ozone_dataframe.plot.line('Month', ['Ozone'], grid = True, figsize=(12, 8))

import pyaf.ForecastEngine as autof
lEngine = autof.cForecastEngine()
lEngine.train(ozone_dataframe , 'Month' , 'Ozone', 12);

At the last 3 lines, I'm getting the error I reported.

**Comment by antoinecarme** [comment]
Thank you for the full copy-paste ... appreciated ;)

However, this seems to be a windows dll install issue with numpy and anaconda ... cannot help. Sorry, this is one reason why I am a very motivated debian user !!!

**Comment by dineshgit** [comment]
The problem is that the locally installed MKL package not compatible with numpy. The solution is install numpy using `conda install numpy` instead of `pip install numpy`.

To find out the MKL library numpy is linked against, run the below Python script in the activated conda environment.

import numpy as np
np.show_config()
