### ISSUE TITLE
hierarchical forecast engine 'forecast' method does not predict future dates

### ISSUE THREAD

**Issue by mgiangreco** [antoinecarme/pyaf#63]
![screenshot 2017-08-31 15 26 09](https://user-images.githubusercontent.com/11744362/29941492-c5f7ae16-8e60-11e7-9124-c68cc160080c.png)

import pyaf.HierarchicalForecastEngine as hautof

lEngine = hautof.cHierarchicalForecastEngine()

lEngine.mOptions.mHierarchicalCombinationMethod = ['OC'];

lEngine.train(weekly_df , 'purchased_at', 'Signal', 26, lHierarchy, None);

df_forecast = lEngine.forecast(iInputDS = weekly_df, iHorizon = 26);

![screenshot 2017-08-31 15 27 55](https://user-images.githubusercontent.com/11744362/29941573-031a3c6e-8e61-11e7-8d4d-a8a865727748.png)

Note that the dates of the forecasts are the same as the dates for the training set.

**Comment by antoinecarme** [comment]
Is you version up-to-date ?

**Comment by mgiangreco** [comment]
Ah yes you did. Many thanks.
