### ISSUE TITLE
support for parallelization

### ISSUE THREAD

**Issue by mgiangreco** [antoinecarme/pyaf#67]
Is pyaf capable of running across several cores or threads? I have a hierarchical dataset of over 1M products and >30 groups.

**Comment by antoinecarme** [comment]
Yes. The best way is to test it ;)

**Comment by mgiangreco** [comment]
How does one specify the number of cores the training should run across?

**Comment by antoinecarme** [comment]
You can look at TS/Options.py for possible customizations.

**Comment by mgiangreco** [comment]
Thanks
