### ISSUE TITLE
PyAF_Introduction notebook hangs on train() call

### ISSUE THREAD

**Issue by tfrojd** [antoinecarme/pyaf#68]
Hi, 

I am quite new to python so I might be screwing something up here but the same thing happened on my work and home computer.

I downloaded anaconda with python 3.6.1 and Jupiter 5.0.0 and followed the install instructions of PyAF from the GitHub repo. Running through the notebook it seems to get stuck on

`lEngine.train(ozone_dataframe , 'Month' , 'Ozone', 12);`

The text says it took you 7 seconds to train but for me it has been running for 15 min on a 2016 macbook and nothing happens except the output

> INFO:pyaf.std:START_TRAINING 'Ozone'

I tried to run it in the ipython terminal with the same result.

Any ideas on how to figure out what is happening?

**Comment by antoinecarme** [comment]
Hi @tfrojd ,

Thanks for using PyAF and hope you'll enjoy.

Seems someone already had this type of problem (https://github.com/antoinecarme/pyaf/issues/39). Python latest version (3.6) is mentioned.

As I mentioned on the homepage., PyAF was tested on a 3.5 python. Also, sorry, not a mac user.

Can you install a python 3.5 or do you really need a 3.6 ?

Hope this helps. Don't hesitate if you have other questions.

**Comment by antoinecarme** [comment]
Just a question, when running ipython in a terminal, when happens when you interrupt the process (hit Ctrl-C) ? any logs to be copy-pasted here ?

**Comment by tfrojd** [comment]
Hi, thanks for your quick reply. I have been experimenting with grouped times series in the R forecast package a bit and PyAF seems really nice.

If I Ctrl-C during the execution I get the following output


[pyaflog.txt](https://github.com/antoinecarme/pyaf/files/1291828/pyaflog.txt)

**Comment by tfrojd** [comment]
Can confirm that a downgrade to Python 3.5.0 solved it.

For mac users running Anaconda it is as simple as 

`conda install python=3.5.0`

**Comment by antoinecarme** [comment]
Thanks a lot for the fix, this will help future users.

Enjoy !!!
