### ISSUE TITLE
Disallow negative predictions?

### ISSUE THREAD

**Issue by mgiangreco** [antoinecarme/pyaf#69]
Is there a way to tell the engine that predictions cannot be negative? Obviously it is possible to change negative predictions to zero after the fact...

**Comment by antoinecarme** [comment]
No, we cannot force the signal to be positive in the engine. A forecast post-processing is an option, as you mentioned.

Do you have a sample code that reproduces this ? I suppose/hope that the error is still acceptable.

Some signal transformations (log) force the signal to be positive at the end, by design. You can activate these (not the default).

**Comment by mgiangreco** [comment]
I'll see if I can get permission to share some anonymized data. I think the issue comes into play when the model chosen by PyAF has a negative sloping trend and a long prediction horizon. In that case the forecast can dip into negative.

**Comment by antoinecarme** [comment]
This is usually needed when the signal values are expected to positive (counts etc).

Think also of a way to force something like this to be always positive : 

![image](https://user-images.githubusercontent.com/16481992/32006375-f8479748-b9a6-11e7-8355-4e70303d0d1f.png)


Here, there are a few points where the forecast is negative.

**Comment by antoinecarme** [comment]
by applying a "relu" rectifier (commonly used in ANNs, https://en.wikipedia.org/wiki/Rectifier_(neural_networks)), one can get the desired forecast, something like : 

```Python
lEngine2.mOptions.mForecastRectifier = "relu"
```

![image](https://user-images.githubusercontent.com/16481992/32046114-5c9b4230-ba42-11e7-92d8-e812641f4678.png)

**Comment by antoinecarme** [comment]
The negative forecasts can now be removed (set to zero) using the training option : 

```Python
 cForecastEngine.mOptions.mForecastRectifier = "relu"
```
