### ISSUE TITLE
unable to handle nan data (follow-up)

### ISSUE THREAD

**Issue by mgiangreco** [antoinecarme/pyaf#71]
Apologies for reopening an issue that was previously closed but I wanted to confirm something.

When I asked about nan values in the signals, you wrote:

"nan is not supported in signals.

Please replace missign data before trying to build a model. I usually add a dataframe.fillnan(0.0) when the missing semantics is zero (when the signal is a count this is OK)"

Imagine you have a dataset where new items are added over time. In this case, the group to which the items belong will have an upward sloping trend (sum of items is increasing), even though the average _per-item_ signal may not be. Is this going to be an issue for the hierarchical PyAF engine? I.e., will the hierarchical engine make forecasts that are too high due to this apparent "increasing" trend at the group level? Or does the reconciliation process account for this?

Thank you.

**Comment by antoinecarme** [comment]
@mgiangreco ,

The answer to your question : nan values have to be imputed and this nothing to do with the way PyAF will perform the modeling/forecasting.

Please, if you need to ask a question, either reopen the previous issue it is related to, or use other means (email, and will give you an answer later).

For organizational reasons, I prefer to have a clean github, no support questions please.

Antoine
