### ISSUE TITLE
Allow use of different matplotlib backends

### ISSUE THREAD

**Issue by bb78657** [antoinecarme/pyaf#89]
pyaf==1.0

In pyaf.TS.Plots.decomp_plot I run unto the warning:

This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

As I am using TkAgg backend for pandas prior to calling pyaf.

Would be good to be able manually set this in pyaf

**Comment by antoinecarme** [comment]
Hi @bb78657 

Thanks for the report.

I added these plot functions to be able to make some plots in the jupyter notebooks based on the forecast results. I am not a plotting/visualization  expert though.

I designed PyAF to be a computational module, not a visualization software. 

A warning is allowed here, if it does not lead to an error.

If you have more sophisiticated use cases, please feel free to use the forecasts and matplotlib.

**Comment by bb78657** [comment]
No worries, not a serious issue, closing this
